# Generated by Django 5.1.6 on 2025-02-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='processModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Process', max_length=100)),
                ('stepOne', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('stepTwo', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('stepThree', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('stepFour', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('stepFive', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usermodel')),
            ],
        ),
    ]
