# Generated by Django 5.1.6 on 2025-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmodel',
            name='stepFive',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='stepFour',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='stepOne',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='stepThree',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='stepTwo',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Incomplete', max_length=100),
        ),
    ]
