# Generated by Django 5.1.6 on 2025-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_processmodel_stepfive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmodel',
            name='stepSix',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Incomplete', max_length=100),
        ),
    ]
