# Generated by Django 5.1.6 on 2025-04-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ', '0001_initial'),
        ('process', '0003_processmodel_stepsix'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmodel',
            name='process',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='process.processmodel'),
            preserve_default=False,
        ),
    ]
