# Generated by Django 5.1.6 on 2025-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ', '0002_rfqmodel_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmodel',
            name='type',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
    ]
