# Generated by Django 5.1.6 on 2025-04-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ', '0003_rfqmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rfqmodel',
            name='name',
        ),
    ]
