# Generated by Django 5.1.6 on 2025-03-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvel', '0002_approvalmodel_response_alter_approvalmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='name',
            field=models.CharField(default='no naaame', max_length=100),
            preserve_default=False,
        ),
    ]
