# Generated by Django 5.1.6 on 2025-04-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0003_processmodel_stepsix'),
    ]

    operations = [
        migrations.CreateModel(
            name='POModel',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_order_number', models.CharField(max_length=200)),
                ('po_date', models.CharField(max_length=200)),
                ('po_name', models.CharField(max_length=200)),
                ('po_address', models.TextField()),
                ('po_email', models.CharField(max_length=200)),
                ('po_mobile_number', models.CharField(max_length=200)),
                ('po_tableData', models.TextField()),
                ('po_term_and_condition', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.processmodel')),
            ],
        ),
    ]
