# Generated by Django 5.1.6 on 2025-04-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodel',
            name='po_invoice',
            field=models.TextField(default='none'),
        ),
    ]
