# Generated by Django 5.1.6 on 2025-02-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepOneModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('requirementSHeet', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.processmodel')),
            ],
        ),
    ]
