# Generated by Django 5.1.6 on 2025-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steponemodel',
            name='SKU',
            field=models.CharField(default='not define', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
