# Generated by Django 5.1.6 on 2025-03-19 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepOne', '0002_steponemodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='steponemodel',
            name='indenting_department',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steponemodel',
            name='justification_for_indenting',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steponemodel',
            name='type_of_item',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
